### ISSUE TITLE
 IE 9 & 10 Support

### ISSUE THREAD

**Issue by epicmiller** [reboundjs/rebound#19]

**Comment by jaminellis** [comment]
At the risk of being stoned... What are the barriers to IE8 support? Is there any interest? (other than from me)

**Comment by epicmiller** [comment]
There are no great polyfills for document.registerElement out there for IE8, and there are many other APIs we are using that would be difficult, if not impossible to shim. HTMLBars is also not planning to support IE8 (that I know of).

However! Rebound is IE9 compatable, and has been since we set up automated Sauce Labs testing :) Closing this now.

**Comment by jaminellis** [comment]
Thank you - IE9 is good news. Hopefully we'll see IE 8 start to tail off soon.
