### ISSUE TITLE
Optimize #each Helper

### ISSUE THREAD

**Issue by epicmiller** [reboundjs/rebound#45]
Minimize dom churn. Right now, an addition will re-render everything after it. That is bad. Lets fix that.

**Comment by matthewrobb** [comment]
Any thoughts on how to tackle this? I've been thinking about it for a while. With Array.obersve you get a mutation notifications that are very specific such as splice and index etc, unfortunately I can't see how you could EASILY get that same information for handlebars collections which are not strictly "ordered" per se.

**Comment by epicmiller** [comment]
In the each helper we are given access to the backbone collection and the containing morph element. The morph element contains a linked list of morphs that, at the moment, are marked with the cid of the model rendering them. We want to listen with backbone evens, because the each helper shouldn't re-render when {silent: true} is passed. I figure we need two passes, one to diff the morph list and collection, and the second to insert or remove elements as needed. At the moment, the helper does one one loop through and when it sees a morph element whos cid attribute does not match the corresponding model it replaces it.

**Comment by epicmiller** [comment]
This was resolved with the upgrade to HTMLBars post-idempotent re-write.
